[global]
pid = /tmp/rl-local-php84-fpm.pid
error_log = /tmp/rl-local-php84-fpm-error.log
daemonize = yes

[www]
listen = 127.0.0.1:9074
pm = dynamic
pm.max_children = 4
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
